import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import * as THREE from 'three';
import {withEmbeddedBoards,xolEmbeddedBoard,sbEmbeddedBoard} from '../site/viewer/embedded-boards.mjs';
import {machineHeadVariants} from '../site/viewer/machine-head-model.mjs';
import {bankChoices,bankPlan,bankCapacity} from '../site/viewer/changer-bank-model.mjs';
const root=path.resolve(process.argv[2]),read=async n=>JSON.parse(await fs.readFile(path.join(root,n),'utf8'));
globalThis.location={href:'https://assets.test/viewer/'};globalThis.fetch=async input=>{let n=String(input).split('?')[0];if(n.includes('ASSET_BUNDLE.json'))return Response.json({encoding:'gzip'});if(n.startsWith('http'))n=new URL(n).pathname.slice(1);else n=n.replace(/^\.\.\//,'');try{return new Response(await fs.readFile(path.join(root,n)))}catch{return new Response('',{status:404})}};
const {createMachineHeads}=await import('../site/viewer/machine-heads.js'),raw=await read('TOOLHEAD_CONFIGURATIONS.json'),heads=withEmbeddedBoards(raw,[xolEmbeddedBoard(await read(raw.base_assets.xol.meta)),sbEmbeddedBoard(await read(raw.base_assets.stealthburner.meta))]),registry=await read('MACHINE_HEAD_REGISTRATIONS.json'),data=await read('TOOLCHANGER_BANK.json');
let combinations=0,meshChecks=0;const machines=[],failures=[];
for(const [machine,binding]of Object.entries(registry.machines))for(const gantry of binding.gantries?Object.keys(binding.gantries):[undefined]){
 const scene=new THREE.Scene(),catalog={...heads,machine_id:machine,variants:machineHeadVariants(heads,registry,machine,gantry),assets:{...heads.assets,...registry.assets,...data.assets},bank_data:data},rig=createMachineHeads(scene,catalog),choices=bankChoices(catalog,data,gantry);assert.equal(choices.length,2,machine+' parked choices');
 for(let count=1;count<=bankCapacity(data,machine);count++)for(let mask=0;mask<2**count;mask++)for(let active=0;active<count;active++){
  const state={enabled:true,active,tools:Array.from({length:count},(_,i)=>choices[mask>>i&1].source_head_configuration)},v=choices[mask>>active&1],plan=bankPlan(state,catalog,data,v);
  await rig.install(v,state);assert.equal(rig.active,v);assert.equal(rig.bankRig.children.length,plan.instances.length);assert.equal(rig.bankRig.children.filter(o=>o.userData.tool_bank.kind==='dock').length,count);
  const boxes=Array.from({length:count},()=>new THREE.Box3());rig.bankRig.updateMatrixWorld(true);
  rig.bankRig.children.forEach((o,i)=>{const p=plan.instances[i];assert.equal(o.userData.tool_bank.slot,p.slot);assert.equal(o.userData.tool_bank.asset,p.id);assert.deepEqual(o.position.toArray(),[p.translation_mm[0]*.001,p.translation_mm[2]*.001,-p.translation_mm[1]*.001]);const hide=new Set(p.hidden_keys||[]);o.traverse(mesh=>{if(!mesh.isMesh)return;const row=rig.cache.get(p.id).loaded.entries.find(e=>e.key===(mesh.userData.part_key||mesh.name));assert(row);assert.notEqual(mesh.material,row.mesh.material,'independent materials');assert.equal(mesh.geometry,row.mesh.geometry,'shared immutable geometry');assert.equal(mesh.visible,!hide.has(row.key)&&!['rail_reference','dock','shuttle_reference'].includes(row.component));if(mesh.visible)boxes[p.slot].expandByObject(mesh);meshChecks++})});
  for(let i=0;i<count;i++){assert(!boxes[i].isEmpty());const frame=data.machines[machine].frame_bounds_mm;assert(boxes[i].min.x>=frame[0][0]*.001+.020-1e-5,machine+' left reserve');assert(boxes[i].max.x<=frame[1][0]*.001-.020+1e-5,machine+' right reserve');if(i)assert(boxes[i].min.x>boxes[i-1].max.x,machine+' adjacent static bank clearance')}
  const fixed=rig.bankRig.children.map(o=>o.getWorldPosition(new THREE.Vector3()).toArray());rig.setDelta([31,-27,80]);rig.bankRig.children.forEach((o,i)=>assert.deepEqual(o.getWorldPosition(new THREE.Vector3()).toArray(),fixed[i]));assert.deepEqual(rig.rig.position.toArray(),[.031,.08,.027]);rig.setPalette({base:'#113355',accent:'#dd4422'});combinations++;
 }
 const before=rig.bankRig.children.map(o=>o.uuid),v=rig.active;data.fixture_assets.push('missing_fixture');await assert.rejects(rig.setBank(rig.bankState));data.fixture_assets.pop();assert.equal(rig.active,v);assert.deepEqual(rig.bankRig.children.map(o=>o.uuid),before);
 await rig.setBank({...rig.bankState,enabled:false});assert.equal(rig.bankRig.children.length,0);assert.equal(rig.active,v);machines.push({machine,gantry,capacity:bankCapacity(data,machine)});console.log(machine+' '+(gantry||'')+' bank combinations passed');
 scene.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}});rig.cache.clear();scene.clear();globalThis.gc?.();
}
const q={all_passed:true,combinations,meshChecks,machines,failures,actual_glbs:true,browser_visual_review:false,full_travel_verified:false};await fs.writeFile(process.argv[3]||'changer-bank-audit.json',JSON.stringify(q,null,2)+'\n');console.log(JSON.stringify(q));
