import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {resolve,dirname,relative,extname} from 'node:path';
import {supportedLanguages} from '../site/viewer/languages.mjs';

const root=new URL('../site/viewer/locales/',import.meta.url);
const inputRoot=new URL('../localization/',import.meta.url);
const languages=supportedLanguages.filter(language=>!['ja','en'].includes(language));
const placeholders=text=>[...text.matchAll(/\{\d+\}/gu)].map(m=>m[0]).sort();
const counts=values=>values.reduce((r,v)=>(r.set(v,(r.get(v)||0)+1),r),new Map());
export function sourceRevision(entry){return createHash('sha256').update(JSON.stringify([entry.kind,entry.ja,entry.en,entry.aliases||[]])).digest('hex').slice(0,20)}
export function compileCatalog(source){
 const entries=Object.fromEntries(Object.entries(source.entries).map(([id,e])=>[id,{...e,revision:sourceRevision(e)}]));
 return '// Generated by scripts/build_locales.mjs. Edit localization/source.json.\nexport const definitions='+JSON.stringify(entries)+';\n';
}
export function validateTranslations(source,dictionaries,glossary={protected_terms:[]}){
 const errors=[],seen=new Set();
 if(source.schema_version!==1||source.source_language!=='en')errors.push({issue:'invalid_source_schema'});
 for(const[id,e]of Object.entries(source.entries)){
  if(!/^[a-z][a-z0-9_.]*$/u.test(id)||!['message','template'].includes(e.kind)||!e.ja?.trim()||!e.en?.trim())errors.push({id,issue:'invalid_source'});
  const key=e.kind+'\0'+e.ja;if(seen.has(key))errors.push({id,issue:'duplicate_source'});seen.add(key);
  if(JSON.stringify(placeholders(e.ja))!==JSON.stringify(placeholders(e.en)))errors.push({id,issue:'source_placeholders'});
  if(e.aliases&&(!Array.isArray(e.aliases)||e.aliases.some(a=>typeof a!=='string'||!a.trim())))errors.push({id,issue:'invalid_aliases'});
  for(const alias of e.aliases||[])if(JSON.stringify(placeholders(alias))!==JSON.stringify(placeholders(e.ja)))errors.push({id,issue:'alias_placeholders'});
 }
 for(const language of languages){
  const locale=dictionaries[language];
  if(locale?.schema_version!==1||locale.language!==language){errors.push({language,issue:'invalid_locale_schema'});continue}
  for(const id of Object.keys(locale.messages))if(!Object.hasOwn(source.entries,id))errors.push({language,id,issue:'orphan'});
  for(const[id,e]of Object.entries(source.entries)){
   const record=locale.messages[id];
   if(!record?.text?.trim()){errors.push({language,id,issue:'missing',source:e.en,expected_revision:sourceRevision(e)});continue}
   if(record.source_revision!==sourceRevision(e))errors.push({language,id,issue:'stale',source:e.en,expected_revision:sourceRevision(e)});
   if(JSON.stringify(placeholders(e.en))!==JSON.stringify(placeholders(record.text)))errors.push({language,id,issue:'placeholders'});
   const sourceNumbers=counts(e.en.match(/\d+(?:\.\d+)*/gu)||[]),targetNumbers=counts(record.text.match(/\d+(?:\.\d+)*/gu)||[]);
   for(const[n,c]of sourceNumbers)if((targetNumbers.get(n)||0)<c)errors.push({language,id,issue:'numeric_value',value:n});
   if(/[\u3040-\u30ff\u3400-\u9fff]/u.test(record.text))errors.push({language,id,issue:'source_script_remaining'});
   if(/RIGENTRY|ZXQ\d+|QXZ/u.test(record.text))errors.push({language,id,issue:'preparation_marker'});
   if(!/[\r\n]/u.test(e.en)&&/[\r\n]/u.test(record.text))errors.push({language,id,issue:'unexpected_line_break'});
   if(!/^\s*,/u.test(e.en)&&/^\s*,/u.test(record.text))errors.push({language,id,issue:'incomplete_clause'});
   for(const code of e.en.match(/\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b/gu)||[]){
    if(!record.text.includes(code))errors.push({language,id,issue:'command_identifier',code});
   }
   for(const rule of glossary.context_rules||[]){
    if(new RegExp(rule.source_pattern,'iu').test(e.en))for(const term of rule.forbidden?.[language]||[]){
     if(record.text.toLowerCase().includes(term.toLowerCase()))errors.push({language,id,issue:'technical_context',term});
    }
   }
   for(const term of glossary.protected_terms||[]){
    const escape=value=>value.replace(/[.*+?^${}()|[\]\\]/gu,'\\$&');
    const pattern=new RegExp('(?<![A-Za-z0-9])'+escape(term)+'(?![A-Za-z0-9])','gu');
    if([...e.en.matchAll(pattern)].length>[...record.text.matchAll(pattern)].length)errors.push({language,id,issue:'protected_term',term});
   }
  }
 }
 return errors;
}
export function compileLocale(locale){
 const records=Object.fromEntries(Object.entries(locale.messages).map(([id,r])=>[id,[r.source_revision,r.text]]));
 return '// Generated by scripts/build_locales.mjs. Edit localization/'+locale.language+'.json.\nexport default '+JSON.stringify(records)+';\n';
}
export const contentRevision=text=>createHash('sha256').update(text.replace(/\r\n/gu,'\n')).digest('hex').slice(0,20);
const digest=contentRevision;
async function cacheReferences(outputs){
 const viewer=fileURLToPath(new URL('../site/viewer/',import.meta.url)),files=new Map();
 async function scan(directory){for(const item of await fs.readdir(directory,{withFileTypes:true})){const path=resolve(directory,item.name);if(item.isDirectory())await scan(path);else if(['.mjs','.js','.html','.css'].includes(extname(path)))files.set(path,await fs.readFile(path,'utf8'))}}
 await scan(viewer);await scan(resolve(viewer,'../fun'));await scan(resolve(viewer,'../support'));
 const changed=new Map(Object.entries(outputs).map(([name,text])=>[fileURLToPath(new URL(name,root)),text]));
 for(const name of ['trident-motion.mjs','baseline-native-datum.mjs','ender-bowden-route.mjs','gcode-panel.js','gcode-preview.mjs','gcode-timeline.mjs','klipper-macro-subset.mjs','virtual-printer-emulator.mjs','gcode-machine-bindings.mjs','gcode-loaded-asset-identity.mjs']){const path=resolve(viewer,name);changed.set(path,await fs.readFile(path,'utf8'));}
 for(const name of ['palette-controller.mjs','micron-native-materials.mjs','appearance-role.mjs','accessories.js','requested-mods.mjs','../REQUESTED_MOD_INSTALLATIONS.json']){const path=resolve(viewer,name);changed.set(path,await fs.readFile(path,'utf8'));}
  for(const name of ['../POSITRON_ASSETS.json','../COMMUNITY_MACHINES_ASSETS.json','model-progress.mjs','model-loader.js','extra-asset-integrity.mjs','extra-machine-loader.mjs','ratrig-loader.mjs','app.js','mercury-tube-routes.mjs','stinger-flex.mjs','community.js','community-state.mjs','community-adapter.mjs','community-loader.mjs','positron.js','positron-fold.mjs','positron-loader.mjs','positron-state.mjs','workspace-navigation.mjs','theme-toggle.css','../fun/fun.css','embed-contract.mjs','workspace-share.mjs','display-start.js','display-preferences.mjs','languages.mjs','translation-engine.mjs','i18n.mjs','messages-en.mjs','machines.js','head-navigation.mjs','machine-head-model.mjs','changer-bank-model.mjs','changer-bank.js','configuration-model.js','configurations.js','configuration-draft.mjs','configuration-editor.mjs','configuration-editor.css','probe-checks.js','toolheads.js','toolchangers.js','crossant-covers.mjs','crossant-adapter.mjs','crossant-loader.mjs','crossant-state.mjs','crossant.js','micron-tube-routes.mjs','micron-flexible.mjs','micron-adapter.mjs','micron.js','workspace-return.mjs','workspace-layout.mjs','workspace-choices.mjs','workspace-ui.mjs','workspace-sections.mjs','workspace-router.mjs','workspace.css']){
   const path=resolve(viewer,name);changed.set(path,await fs.readFile(path,'utf8'));
  }
 for(const name of ['../SIBOOR_TRIDENT_ASSETS.json','../HEAD_ADDITIONS.json','head-additions.mjs','siboor-machine.mjs','siboor-catalog.mjs','bootstrap.js','asset-availability.js','machine-heads.js','frame-mods.js','flexible.js','product-links.js','custom-voron.js','custom-voron-tube.mjs','v24-ptfe.mjs','custom-voron-loader.mjs','custom-voron-state.mjs','native-motion-profile.mjs','native-motion-flex.mjs','native-motion-controls.mjs','annex.js','kit-reference.js','component-assets.mjs','v0-mod-library.mjs']){
  const path=resolve(viewer,name);changed.set(path,await fs.readFile(path,'utf8'));
 }
 // Content revisions propagate from dictionaries to their importers and page
 // controllers. Revising copy does not depend on remembering a cache suffix.
 for(let pass=0;pass<30;pass++){
  let progress=false;
  for(const[path,original]of files){
   if(relative(viewer,path).replaceAll('\\','/').startsWith('locales/'))continue;
   const before=changed.get(path)??original;
   const after=before.replace(/(['"])(\.{1,2}\/[^'"\s?#]+\.(?:mjs|js|css|json))(?:\?v=[^'"\s]+)?\1/gu,(token,quote,name)=>{
    const target=resolve(dirname(path),name);if(target===path||!changed.has(target))return token;
    return quote+name+'?v='+digest(changed.get(target))+quote;
   });
   if(after!==before){changed.set(path,after);progress=true}
  }
  if(!progress)return changed;
 }
 throw Error('Locale import graph contains a cache-reference cycle.');
}
async function main(){
 const source=JSON.parse(await fs.readFile(new URL('source.json',inputRoot),'utf8'));
 const dictionaries=Object.fromEntries(await Promise.all(languages.map(async language=>[language,JSON.parse(await fs.readFile(new URL(language+'.json',inputRoot),'utf8'))])));
 const glossary=JSON.parse(await fs.readFile(new URL('glossary.json',inputRoot),'utf8'));
 const errors=validateTranslations(source,dictionaries,glossary);
 if(process.argv.includes('--report')){console.log(JSON.stringify({entries:Object.keys(source.entries).length,errors},null,2));process.exitCode=errors.length?1:0;return}
 if(errors.length)throw Error('Translation checks failed: '+JSON.stringify(errors.slice(0,30))+'; total '+errors.length);
 const outputs={'catalog.mjs':compileCatalog(source),...Object.fromEntries(languages.map(language=>[language+'.mjs',compileLocale(dictionaries[language])]))};
 outputs['manifest.mjs']='// Generated locale revisions; no online translation at runtime.\nexport {definitions} from \'./catalog.mjs?v='+digest(outputs['catalog.mjs'])+'\';\nexport const localeLoaders={'+languages.map(language=>language+':()=>import(\'./'+language+'.mjs?v='+digest(outputs[language+'.mjs'])+'\')').join(',')+'};\n';
 for(const[path,text]of await cacheReferences(outputs)){
  if(process.argv.includes('--write'))await fs.writeFile(path,text);
  else if(await fs.readFile(path,'utf8')!==text)throw Error('Generated locale differs: '+relative(fileURLToPath(root),path)+'; run node scripts/build_locales.mjs --write after reviewing translations.');
 }
 console.log(`Locale catalog checks passed: ${Object.keys(source.entries).length} stable IDs, ${languages.join('/')}; revisions, placeholders and numeric values checked.`);
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===resolve(process.argv[1]))await main();
