import assert from 'node:assert/strict';
import {AccessorySelection,accessoryIds,accessoryAvailable} from '../site/viewer/accessories.js';
import {mergeRequestedMods} from '../site/viewer/requested-mods.mjs';
const catalog={accessories:[{id:'bedfans',module:'bedfans'},{id:'other',module:'other'}]};
const fan={root:{visible:false,userData:{},position:{set(...p){this.value=p}}}};
let updates=0;
const state=new AccessorySelection(catalog,async id=>{if(id==='other')throw Error('Failed download');return fan},()=>updates++);
assert.deepEqual(state.saved(),{accessories:[]});
await state.apply({accessories:['bedfans','bedfans']});
assert.deepEqual(state.saved(),{accessories:['bedfans']});
assert.equal(fan.root.visible,true);assert.equal(fan.root.userData.headModule,false);
// Installing another head resets loaded roots; the accessory choice survives.
fan.root.visible=false;fan.root.position.set(1,2,3);state.refresh();
assert.equal(fan.root.visible,true);assert.deepEqual(fan.root.position.value,[0,0,0]);
await assert.rejects(state.apply({accessories:['other']}));
assert.equal(fan.root.visible,true);assert.deepEqual(state.saved(),{accessories:['bedfans']});
await state.apply({});assert.equal(fan.root.visible,false);assert.equal(updates,2);
catalog.accessories[0].translation_mm=[0,-.0000011205679,.3000000000021];
await state.apply({accessories:['bedfans']});
assert.deepEqual(fan.root.position.value,[0,.3000000000021/1000,.0000011205679/1000]);
assert.throws(()=>accessoryIds(catalog,{accessories:['https://example.com/model.glb']}));
assert.throws(()=>accessoryIds(catalog,{accessories:'bedfans'}));
const shared={root:{visible:false,userData:{},position:{set(){}}}},cheese={root:{visible:false,userData:{},position:{set(){}}}},hex={root:{visible:false,userData:{},position:{set(){}}}};
const stock=new Map([['skirt',{visible:true}],['screw',{visible:true}],['panel',{visible:false}]]);
const skins={accessories:[{id:'cheese',modules:['common','cheese'],exclusive_group:'skirts',hidden_stock_keys:['skirt','screw','panel']},{id:'hex',modules:['common','hex'],exclusive_group:'skirts',hidden_stock_keys:['skirt','screw','panel']},{id:'bad',modules:['missing'],hidden_stock_keys:['skirt']}]};
const replacements=new AccessorySelection(skins,async id=>{if(id==='missing')throw Error('404');return {common:shared,cheese,hex}[id]},()=>{},stock);
await replacements.apply({accessories:['cheese']});assert(!stock.get('skirt').visible&&!stock.get('screw').visible);assert(shared.root.visible&&cheese.root.visible&&!hex.root.visible);
await replacements.apply({accessories:['hex']});assert(shared.root.visible&&hex.root.visible&&!cheese.root.visible);
assert.throws(()=>accessoryIds(skins,{accessories:['hex','cheese']}));
await assert.rejects(replacements.apply({accessories:['bad']}));assert(shared.root.visible&&hex.root.visible&&!stock.get('skirt').visible);
stock.get('skirt').visible=true;shared.root.visible=false;replacements.refresh();assert(!stock.get('skirt').visible&&shared.root.visible);
await replacements.apply({});assert(stock.get('skirt').visible&&stock.get('screw').visible&&!stock.get('panel').visible);assert(!shared.root.visible&&!hex.root.visible);
const constrained={accessories:[{id:'motor_fan',module:'fan',gantry_ids:['r2'],hidden_stock_keys:['screw']}]};
let variant={gantry:'r2'};
const scoped=new AccessorySelection(constrained,async()=>fan,()=>{},stock,()=>variant);
await scoped.apply({accessories:['motor_fan']});assert(fan.root.visible&&!stock.get('screw').visible);
variant={gantry:'awd'};scoped.refresh();assert(!fan.root.visible&&stock.get('screw').visible);assert.deepEqual(scoped.saved(),{accessories:[]});
await assert.rejects(scoped.apply({accessories:['motor_fan']}));assert(stock.get('screw').visible);
variant={gantry:'r2'};await scoped.apply({accessories:['motor_fan']});assert(fan.root.visible);
assert(accessoryAvailable({id:'legacy'},null));assert(!accessoryAvailable(constrained.accessories[0],null));
const scopedHead={gantry_ids:['r2'],compatible_selection:{toolhead:'stealthburner',mount:'fixed'}};
assert(accessoryAvailable(scopedHead,{gantry:'r2',toolhead:'stealthburner',mount:'fixed'}));
assert(!accessoryAvailable(scopedHead,{gantry:'r2',toolhead:'sphinx',mount:'fixed'}));
assert(!accessoryAvailable(scopedHead,{gantry:'r2',toolhead:'stealthburner',mount:'stealthchanger'}));
const review={finite_mating_passed:true,unintended_body_interference_passed:true,whole_machine_certified:false,inputs:[{sha256:'a'.repeat(64)}]};
const additions={schema:'requested-native-mod-installations-v1',assets:{fan:{}},machines:{host:{accessories:[{...constrained.accessories[0],geometry_review:review}]}}};
assert.equal(mergeRequestedMods({assets:{},accessories:[]},additions,'host').accessories.length,1);
assert.equal(mergeRequestedMods({assets:{},accessories:[]},additions,'other').accessories.length,0);
assert.throws(()=>mergeRequestedMods({assets:{fan:{}},accessories:[]},additions,'host'));
assert.throws(()=>mergeRequestedMods({assets:{},accessories:constrained.accessories},additions,'host'));
assert.throws(()=>mergeRequestedMods({assets:{},accessories:[]},{...additions,assets:{}},'host'));
const rejected=structuredClone(additions);rejected.machines.host.accessories[0].geometry_review.unintended_body_interference_passed=false;
assert.throws(()=>mergeRequestedMods({assets:{},accessories:[]},rejected,'host'));
console.log('Accessory selection passed: toggle, failed asset rollback, stock restoration, scoped gantry switching and native registry failures.');
