import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {readSupportJSON,validateSupportResource,supportDownloadBlob} from '../site/support/resource.mjs';

const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
const original={schema:1,rows:Array.from({length:200},(_,i)=>[i,'日本語 한국어 Русский Español']),notes:['Native findings remain open']};
const decoded=Buffer.from(JSON.stringify(original)+'\n'),encoded=gzipSync(decoded,{level:9});
const resource={file:'machine.json.gz',encoding:'gzip',bytes:encoded.length,sha256:digest(encoded),decoded_bytes:decoded.length,decoded_sha256:digest(decoded)};
let requested;
const fetcher=async(url,options)=>{requested={url,options};return new Response(encoded)};
assert.deepEqual(await readSupportJSON('machine.json',{resource,fetcher}),original);
assert.equal(await supportDownloadBlob(original).text(),decoded.toString('utf8'),'Configuration downloads retain the original JSON instead of exposing compressed transport');
assert.equal(requested.url,'./data/machine.json.gz');assert.equal(requested.options.cache,'no-cache');
assert(encoded.length<decoded.length/3,'Repeated configuration rows must reduce transport bytes');
assert.deepEqual(await readSupportJSON('machine.json',{resource,fetcher:async()=>new Response(decoded,{headers:{'Content-Encoding':'gzip'}})}),original,'Host-decoded JSON must retain its exact decoded checksum');
assert.deepEqual(await readSupportJSON('index.json',{fetcher:async()=>new Response(JSON.stringify({targets:[]}))}),{targets:[]});
for(const [field,value]of [['file','../machine.json.gz'],['encoding','br'],['bytes',0],['decoded_bytes',32*1024*1024+1],['sha256','invalid'],['decoded_sha256','']])assert.throws(()=>validateSupportResource('machine.json',{...resource,[field]:value}));
assert.throws(()=>validateSupportResource('../machine.json',resource));
await assert.rejects(readSupportJSON('machine.json',{resource,fetcher:async()=>new Response(encoded,{status:404})}));
await assert.rejects(readSupportJSON('machine.json',{resource,fetcher:async()=>new Response(null,{status:204})}));
const corrupted=Buffer.from(encoded);corrupted[corrupted.length-7]^=1;
await assert.rejects(readSupportJSON('machine.json',{resource,fetcher:async()=>new Response(corrupted)}),/checksum mismatch/u);
await assert.rejects(readSupportJSON('machine.json',{resource:{...resource,decoded_sha256:'0'.repeat(64)},fetcher}),/Decoded support resource checksum/u);
await assert.rejects(readSupportJSON('machine.json',{resource,fetcher:async()=>new Response(Buffer.from('{}'))}),/Decoded support resource checksum/u);
await assert.rejects(readSupportJSON('machine.json',{resource:{...resource,decoded_bytes:decoded.length-1},fetcher}),/declared size/u);
let canceled=false;
const endless=new ReadableStream({pull(controller){controller.enqueue(new Uint8Array(1024))},cancel(){canceled=true}});
await assert.rejects(readSupportJSON('machine.json',{resource:{...resource,bytes:20,decoded_bytes:30},fetcher:async()=>new Response(endless)}),/declared size/u);
assert(canceled,'Oversized streams must stop instead of retaining unbounded output');
const truncated=encoded.subarray(0,encoded.length-8);
await assert.rejects(readSupportJSON('machine.json',{resource:{...resource,bytes:truncated.length,sha256:digest(truncated)},fetcher:async()=>new Response(truncated)}));
const invalidUTF=Buffer.from([0xff,0xff]);
await assert.rejects(readSupportJSON('machine.json',{resource:{...resource,decoded_bytes:2,decoded_sha256:digest(invalidUTF)},fetcher:async()=>new Response(invalidUTF)}));
console.log('Support delivery: exact decoded catalogs, transport hashes, host decoding, corrupt/truncated data and bounded streams passed.');
