import assert from 'node:assert/strict';
import {compileGcode} from '../site/viewer/gcode-preview.mjs';
import {compileVirtualPrinter,virtualSettingsFromAdapter} from '../site/viewer/virtual-printer-emulator.mjs';
const basic={initial:[10,20,30],limits:{X:[0,200],Y:[0,200],Z:[0,200]}};
const measured={...basic,require_homing:true,homing:Object.fromEntries(['X','Y','Z'].map((a,i)=>[a,{position_mm:[0,0,100][i],evidence:'TEST FIXTURE contact; not native CAD'}])),probe:{contact_nozzle_z_mm:1.5,offset_xy_mm:[5,-2],xy_limits_mm:[[0,200],[0,200]],evidence:'TEST FIXTURE planar contact'},heaters:{extruder:{temperature_c:20,min_c:0,max_c:300,min_extrude_c:170},extruder1:{temperature_c:20,min_c:0,max_c:300,min_extrude_c:170},heater_bed:{temperature_c:20,min_c:0,max_c:120}},tools:['extruder','extruder1'],extrusion_mode:'temperature_guard'};
const run=(text,settings=basic,macros='')=>compileVirtualPrinter(text,{settings,macros});
let r=run('G28\nG1 X30 Y30 F600\nPROBE\nM104 S200\nM109 S200\nM190 S60\nM83\nG1 E2\nACTIVATE_EXTRUDER EXTRUDER=extruder1\nM109 S210\nG1 E3\nM106 S128\nM107\nTURN_OFF_HEATERS',measured);
assert.equal(r.error,null);assert.equal(r.physical_machine_connected,false);assert.deepEqual(r.final.position,[30,30,1.5,5]);assert.deepEqual(r.final.homed_axes,['X','Y','Z']);assert.deepEqual(r.final.probe_result.probe_xy_mm,[35,28]);assert.equal(r.final.active_tool,'extruder1');assert.deepEqual(r.final.extrusion_by_tool,{extruder:2,extruder1:3});assert.equal(r.final.heaters.extruder1.temperature_c,210);assert.equal(r.final.heaters.extruder1.target_c,0);assert(r.time_excludes_thermal_waits);
for(const event of r.events.filter(e=>['home_contact','probe_contact','tool_exchange'].includes(e.kind))){assert.equal(event.draw_path,false);assert.equal(event.duration_s,0);assert.equal(event.distance_mm,0);assert.equal(event.data.trajectory_verified,false)}
assert.equal(r.events.find(e=>e.kind==='tool_exchange').data.installed_geometry_changed,false);
for(const text of ['G28','PROBE','M104 S200','T1','SET_PIN PIN=relay VALUE=1','UPDATE_DELAYED_GCODE ID=x DURATION=1','SAVE_CONFIG','FIRMWARE_RESTART','M112','RUN_SHELL_COMMAND CMD=x','BED_MESH_CALIBRATE','SET_DUAL_CARRIAGE CARRIAGE=1 MODE=COPY']){r=run('G1 X11\n'+text+'\nG1 X12');assert(r.error,text);assert.equal(r.error.line,2);assert.equal(r.final.position[0],11);assert.equal(r.events.length,1,text)}
for(const text of ['G1 X11','G28 Q1','PROBE SAMPLES=3','M104 S301','M104 S200 T2','M104 S200 Q1','M104 S200 S100','M190 S-1','M106 S256','ACTIVATE_EXTRUDER EXTRUDER=unknown','G1 E1','SET_HEATER_TEMPERATURE HEATER=missing TARGET=100','TEMPERATURE_WAIT SENSOR=extruder','TEMPERATURE_WAIT SENSOR=extruder MINIMUM=200 MAXIMUM=100']){r=run(text,measured);assert(r.error,text);assert.deepEqual(r.final.position,[10,20,30,0],text);assert.equal(r.final.heaters.extruder.target_c,0,text)}
r=run('G28 X\nG1 X20\nG1 Y25',measured);assert.equal(r.error.line,3);assert.deepEqual(r.final.homed_axes,['X']);assert.deepEqual(r.final.position,[20,20,30,0]);
r=run('G28\nG1 X198 Y10\nPROBE',measured);assert.match(r.error.message,/region/);
r=run('G28\nM104 S200\nTEMPERATURE_WAIT SENSOR=extruder MINIMUM=190 MAXIMUM=205\nG1 E1',measured);assert.equal(r.error,null);assert.equal(r.final.heaters.extruder.temperature_c,200);
r=run('M104 S200\nG4 P1000',measured);assert.equal(r.final.heaters.extruder.temperature_c,20);assert.equal(r.final.heaters.extruder.target_c,200);
const macroConfig='[gcode_macro OUTER]\nvariable_x: 2\ngcode:\n  G1 X20\n  G1 Y{printer.toolhead.position[0]}\n  INNER\n[gcode_macro INNER]\ngcode:\n  G1 Z{printer.toolhead.position[0]}\n  SET_GCODE_VARIABLE MACRO=OUTER VARIABLE=x VALUE=4\n[gcode_macro T1]\ngcode:\n  ACTIVATE_EXTRUDER EXTRUDER=extruder1';
r=run('OUTER\nT1', {...measured,require_homing:false},macroConfig);assert.equal(r.error,null);assert.deepEqual(r.final.position,[20,10,20,0]);assert.equal(r.final.macro_variables.OUTER.x,4);assert.equal(r.final.active_tool,'extruder1');assert.equal(r.events.find(e=>e.command==='G1'&&e.text.startsWith('G1 Z')).source.macro,'INNER');
const variableConfig='[gcode_macro V]\nvariable_n: 1\ngcode:\n  SET_GCODE_VARIABLE MACRO=V VARIABLE=n VALUE=2\n  G1 X{printer["gcode_macro V"].n}';
r=run('V\nV',basic,variableConfig);assert.equal(r.error,null);assert.deepEqual(r.events.filter(e=>e.command==='G1').map(e=>e.to[0]),[1,2]);
r=run('LOOP',basic,'[gcode_macro LOOP]\ngcode:\n  LOOP');assert.match(r.error.message,/depth/);assert.equal(r.events.length,8);
assert.throws(()=>run('G21',basic,'[gcode_macro G1]\ngcode:\n  G21'),/override/);
r=compileVirtualPrinter('MANY',{settings:basic,maxLines:5,macros:'[gcode_macro MANY]\ngcode:\n  {% for i in range(10) %}\n  G4 P1\n  {% endfor %}'});assert.match(r.error.message,/budget/);assert.equal(r.events.length,5);
r=run('G21\nBAD',basic,'[gcode_macro BAD]\ngcode:\n  G1 X{params.MISSING}');assert.match(r.error.message,/defined/);assert.equal(r.events.length,1);
r=run('G1 X15\nBAD',basic,'[gcode_macro BAD]\ngcode:\n  M112');assert.equal(r.error.source.macro,'BAD');assert.equal(r.error.source.macro_line,1);assert.equal(r.final.position[0],15);
const legacy='G21\nG90\nG1 X40 Y30 F600\nM83\nG1 E2\nSAVE_GCODE_STATE NAME=a\nG91\nG1 X10\nRESTORE_GCODE_STATE NAME=a MOVE=1';
const old=compileGcode(legacy,basic),fresh=run(legacy);assert.equal(fresh.error,null);assert.deepEqual(fresh.final.position,old.final.position);assert.equal(fresh.duration_s,old.duration_s);assert.deepEqual(fresh.events.map(e=>[e.from,e.to,e.duration_s]),old.events.map(e=>[e.from,e.to,e.duration_s]));
const defaults=virtualSettingsFromAdapter({profile:{display_reference_xyz_mm:basic.initial,display_limits_mm:basic.limits,bed_top_world_z_mm:0}});assert.deepEqual(defaults.homing,{});assert.equal(defaults.probe,null);assert.deepEqual(defaults.heaters,{});assert.equal(run('G28',defaults).complete,false);
for(const settings of [{...measured,homing:{X:{position_mm:0}}},{...measured,probe:{...measured.probe,evidence:''}},{...basic,tools:['constructor']},{...basic,heaters:{extruder:{temperature_c:20,min_c:25,max_c:300}}},{...basic,require_homing:'true'},{...basic,initial_homed_axes:['x']},{...basic,extrusion_mode:'temperature_guard'}])assert.throws(()=>run('G21',settings));
console.log('Virtual printer: legacy compatibility, snapshot expansion, variables, measured contact gates, logical heat/tools, extrusion guard, atomic rejection and budgets passed.');
