import assert from 'node:assert/strict';
import {PerspectiveCamera, Vector3} from '../site/viewer/vendor/three.module.js';
import {setResponsiveAspect, frameResponsiveView} from '../site/viewer/responsive-camera.mjs';

const camera = new PerspectiveCamera(35, 1, .01, 100);
const target = new Vector3(.2, .3, -.1);
camera.position.copy(target).add(new Vector3(0, 0, 2));
const controls = {target, update() { camera.lookAt(target); camera.updateMatrixWorld(); }};
const close = (a, b) => assert.ok(Math.abs(a - b) < 1e-9, `${a} != ${b}`);
setResponsiveAspect(camera, controls, 1000, 600);
const distance = camera.position.distanceTo(target);
const point = target.clone().add(new Vector3(.25, 0, 0));
const screenFraction = (width, height) => point.clone().project(camera).x * width / Math.min(width, height);
const initial = screenFraction(1000, 600);
setResponsiveAspect(camera, controls, 390, 700);
close(screenFraction(390, 700), initial);
const direction = camera.position.clone().sub(target).normalize();
close(direction.z, 1);
const portraitDistance = camera.position.distanceTo(target);
setResponsiveAspect(camera, controls, 390, 700);
close(camera.position.distanceTo(target), portraitDistance);
setResponsiveAspect(camera, controls, 1000, 600);
close(camera.position.distanceTo(target), distance);
setResponsiveAspect(camera, controls, 390, 700);
camera.position.copy(target).add(new Vector3(0, 0, 2));
frameResponsiveView(camera, controls);
close(camera.position.distanceTo(target), portraitDistance);
setResponsiveAspect(camera, controls, 0, 0);
assert.ok(Number.isFinite(camera.position.length()));
console.log('Responsive camera: portrait framing, panel fold round trip, stable repeated resize, target/direction preservation and preset framing passed.');
