import assert from 'node:assert/strict';
import {AccessorySelection,accessoryIds} from '../site/viewer/accessories.js';
const catalog={accessories:[{id:'bedfans',module:'bedfans'},{id:'other',module:'other'}]};
const fan={root:{visible:false,userData:{},position:{set(...p){this.value=p}}}};
let updates=0;
const state=new AccessorySelection(catalog,async id=>{if(id==='other')throw Error('Failed download');return fan},()=>updates++);
assert.deepEqual(state.saved(),{accessories:[]});
await state.apply({accessories:['bedfans','bedfans']});
assert.deepEqual(state.saved(),{accessories:['bedfans']});
assert.equal(fan.root.visible,true);assert.equal(fan.root.userData.headModule,false);
// Installing another head resets loaded roots; the accessory choice survives.
fan.root.visible=false;fan.root.position.set(1,2,3);state.refresh();
assert.equal(fan.root.visible,true);assert.deepEqual(fan.root.position.value,[0,0,0]);
await assert.rejects(state.apply({accessories:['other']}));
assert.equal(fan.root.visible,true);assert.deepEqual(state.saved(),{accessories:['bedfans']});
await state.apply({});assert.equal(fan.root.visible,false);assert.equal(updates,2);
catalog.accessories[0].translation_mm=[0,-.0000011205679,.3000000000021];
await state.apply({accessories:['bedfans']});
assert.deepEqual(fan.root.position.value,[0,.3000000000021/1000,.0000011205679/1000]);
assert.throws(()=>accessoryIds(catalog,{accessories:['https://example.com/model.glb']}));
assert.throws(()=>accessoryIds(catalog,{accessories:'bedfans'}));
const shared={root:{visible:false,userData:{},position:{set(){}}}},cheese={root:{visible:false,userData:{},position:{set(){}}}},hex={root:{visible:false,userData:{},position:{set(){}}}};
const stock=new Map([['skirt',{visible:true}],['screw',{visible:true}],['panel',{visible:false}]]);
const skins={accessories:[{id:'cheese',modules:['common','cheese'],exclusive_group:'skirts',hidden_stock_keys:['skirt','screw','panel']},{id:'hex',modules:['common','hex'],exclusive_group:'skirts',hidden_stock_keys:['skirt','screw','panel']},{id:'bad',modules:['missing'],hidden_stock_keys:['skirt']}]};
const replacements=new AccessorySelection(skins,async id=>{if(id==='missing')throw Error('404');return {common:shared,cheese,hex}[id]},()=>{},stock);
await replacements.apply({accessories:['cheese']});assert(!stock.get('skirt').visible&&!stock.get('screw').visible);assert(shared.root.visible&&cheese.root.visible&&!hex.root.visible);
await replacements.apply({accessories:['hex']});assert(shared.root.visible&&hex.root.visible&&!cheese.root.visible);
assert.throws(()=>accessoryIds(skins,{accessories:['hex','cheese']}));
await assert.rejects(replacements.apply({accessories:['bad']}));assert(shared.root.visible&&hex.root.visible&&!stock.get('skirt').visible);
stock.get('skirt').visible=true;shared.root.visible=false;replacements.refresh();assert(!stock.get('skirt').visible&&shared.root.visible);
await replacements.apply({});assert(stock.get('skirt').visible&&stock.get('screw').visible&&!stock.get('panel').visible);assert(!shared.root.visible&&!hex.root.visible);
console.log('Accessory selection passed: toggle, head switch, JSON round trip, failed asset preservation and whitelist.');
