import assert from 'node:assert/strict';
import {printerWorkspaceURL,workspaceKindFor} from '../site/viewer/workspace-return.mjs';
const base='https://example.test/3d-print-rig/viewer/';
const saved=base+'v24-reference.html?machine=voron_v24_300_printed&configuration=monolith_machine__kept&lang=ja';
assert.equal(printerWorkspaceURL(base+'toolheads.html?lang=ja',saved),saved);
assert.equal(new URL(printerWorkspaceURL(base+'components.html?lang=en',saved)).searchParams.get('lang'),'en');
const returned=new URL(printerWorkspaceURL(base+'toolheads.html?return_machine=voron_trident_250&return_configuration=installed_head&lang=ja',saved));
assert.equal(returned.pathname,'/3d-print-rig/viewer/trident.html');
assert.equal(returned.searchParams.get('machine'),'voron_trident_250');
assert.equal(returned.searchParams.get('configuration'),'installed_head');
assert.equal(printerWorkspaceURL(saved,base+'?machine=siboor_trident_350'),saved);
const index=base+'index.html?machine=siboor_trident_350&configuration=installed&bank=kept';
assert.equal(printerWorkspaceURL(index),index);
assert.equal(printerWorkspaceURL(base+'components.html',index),index);
assert.equal(printerWorkspaceURL(base+'cleaning.html?lang=ja',saved),saved);
assert.equal(printerWorkspaceURL(base+'gantries.html?lang=en',saved).includes('voron_v24_300_printed'),true);
for(const invalid of ['https://other.test/viewer/?machine=siboor_trident_350',base+'toolheads.html?machine=voron_v24_300_printed',base+'?machine=missing','not a URL'])assert.equal(printerWorkspaceURL(base+'components.html',invalid),base);
assert.equal(printerWorkspaceURL(base+'toolheads.html?return_machine=unknown',saved),saved);
assert.equal(workspaceKindFor('e3ng.html'),'toolchangers');
assert.equal(workspaceKindFor('trident.html'),'printer');
assert.equal(workspaceKindFor('toolheads.html'),'toolheads');
assert.equal(printerWorkspaceURL(base+'e3ng.html?machine=e3ng_toolchanger_230',saved),saved);
assert.equal(printerWorkspaceURL(base+'components.html',base+'e3ng.html?machine=e3ng_toolchanger_230'),base);
console.log('Workspace return links preserve the actual machine, complete configuration and language; invalid references cannot redirect off-site.');
