import assert from 'node:assert/strict';
import {register} from 'node:module';
register('./three-test-loader.mjs',import.meta.url);
const THREE=await import('three');
const {createToolheadLedRig}=await import('../site/viewer/toolhead-lighting.mjs');
const {cloneNativeLedTree}=await import('../site/viewer/led-emission-surface.mjs');
const {sourceLedIdentity}=await import('../site/viewer/toolhead-led-identities.mjs');
const scene=new THREE.Scene(),parent=new THREE.Group();scene.add(parent);
const mesh=new THREE.Mesh(new THREE.BoxGeometry(.005,.005,.001),new THREE.MeshStandardMaterial({color:0xc5c2a3}));mesh.name='fixture-native-logo';parent.add(mesh);
const original=mesh.geometry,originalMaterial=mesh.material;
const rig=createToolheadLedRig(scene,{identify:o=>o===mesh?{id:'fixture-source-disc',normal:[0,0,1],kind:'logo'}:null,apertureFor:()=>null});
assert.deepEqual(rig.update({power:true,color:'red'}),{installed:1,lit:1,registered:1});assert.equal(mesh.children.filter(o=>o.isPointLight).length,1);
assert.deepEqual(rig.emitters[0].light.matrixWorld.elements.slice(12,15),rig.emitters[0].light.position.toArray(),'The first render must use the attached LED position before another scene matrix update');
const initial=mesh.material.emissive.clone();rig.update({color:'rainbow',effect:'flow',seconds:0});const a=mesh.material.emissive.clone();rig.update({color:'rainbow',effect:'flow',seconds:1});assert(!mesh.material.emissive.equals(a));
for(const delta of [[0,0,0],[.08,.12,.2],[-.04,0,0],[0,0,0]]){parent.position.set(...delta);scene.updateMatrixWorld(true);const e=rig.emitters[0],actual=e.light.getWorldPosition(new THREE.Vector3());assert(actual.equals(e.light.position.clone().add(parent.position)));assert.equal(rig.update().installed,1);}
parent.visible=false;assert.equal(rig.update().installed,0);assert.equal(rig.emitters[0].light.intensity,0);assert.equal(mesh.material.emissiveIntensity,0);
parent.visible=true;assert.equal(rig.update({power:false}).lit,0);assert.equal(rig.emitters[0].light.intensity,0);assert.equal(rig.update({power:true}).lit,1);
assert.equal(sourceLedIdentity(new THREE.Mesh(new THREE.BoxGeometry(.005,.005,.001),originalMaterial)),null,'Unknown purchased object must not become an LED');
const optical=new THREE.Mesh(new THREE.BoxGeometry(.005,.005,.001),originalMaterial);optical.name='a4t106_led_diffuser';assert.equal(sourceLedIdentity(optical),null,'A4T printed diffuser is not an installed LED');
parent.remove(mesh);assert.equal(rig.update().registered,0);assert.equal(mesh.geometry,original);assert.equal(mesh.material,originalMaterial);assert.equal(mesh.children.length,0);
parent.add(mesh);assert.equal(rig.update().installed,1,'Reattached native emitter must be registered again');assert.equal(mesh.children.filter(o=>o.isPointLight).length,1);
rig.dispose();assert.equal(rig.emitters.length,0);
const guide=new THREE.Mesh(new THREE.BoxGeometry(.002,.002,.001),originalMaterial),parked=new THREE.Group();parked.add(guide);scene.add(parked);
const bank=new THREE.Group();scene.add(bank);bank.add(parent,parked);
const guided=createToolheadLedRig(scene,{identify:o=>o===mesh?{id:'fixture-source-disc',normal:[0,0,1],kind:'logo'}:null,apertureFor:()=>null,guideFor:o=>o===guide?{emitter_id:'fixture-source-disc'}:null});
guided.update();assert.equal(guide.material.emissiveIntensity,0,'A different parked head cannot illuminate an empty optical guide');
parent.add(guide);guided.update();assert(guide.material.emissiveIntensity>0);assert(guide.material.emissive.equals(mesh.material.emissive));
originalMaterial.color.set('#00ffff');guided.update();assert.equal(guide.material.color.getHexString(),'00ffff','A printed optical guide must keep following its palette');
const nativeClone=cloneNativeLedTree(parent),clonedEmitter=nativeClone.children.find(o=>o.name===mesh.name),clonedGuide=nativeClone.children.find(o=>o.isMesh&&o!==clonedEmitter);assert.equal(clonedEmitter.geometry,original);assert.equal(clonedEmitter.children.length,0);assert(!clonedEmitter.userData.ledSurface);assert(!clonedGuide.userData.ledGuide);assert.equal(clonedGuide.material,originalMaterial);assert(mesh.userData.ledSurface);assert(guide.userData.ledGuide);assert.equal(mesh.children.filter(o=>o.isPointLight).length,1);
guided.update({power:false});assert.equal(guide.material.emissiveIntensity,0);assert.equal(guide.material.color.getHex(),originalMaterial.color.getHex());
guided.dispose();assert.equal(guide.material,originalMaterial);assert.equal(mesh.geometry,original);
console.log('Toolhead LED controller: source-only targeting, RGB timing, parent motion, hidden/obsolete roots, power, material isolation and exact teardown passed.');
