import assert from 'node:assert/strict';
import {machineHeadVariants,installedHeadPlan} from '../site/viewer/machine-head-model.mjs';
import {headPlan} from '../site/viewer/head-assembly.js';
import {choicesFor,resolveVariant} from '../site/viewer/configuration-model.js';
import {headPrinterLink} from '../site/viewer/head-navigation.mjs';
const reg={sources:{filamatrix:{origin_mm:[0,29.1,50.9]},madmax_xol:{origin_mm:[0,9.4,0]}},machines:{voron_trident_350:{origin_mm:[0,-7,360],belt_width_mm:6,xy_motors:2},siboor_trident_350:{gantries:{siboor_awd:{origin_mm:[0,0,360],belt_width_mm:9,xy_motors:4}}}},assets:{}};
const c={dimensions:['toolhead','mount','extruder','hotend','gantry','carriage','probe','board','cooling'],variants:[],toolheads:[{id:'stealthburner'},{id:'xol'}],mounts:[{id:'filamatrix'},{id:'madmax'}],extruders:[{id:'cw2'},{id:'galileo2'},{id:'sherpa_mini'}],hotends:[{id:'revo_voron'},{id:'rapido1_hf'},{id:'rapido1_uhf'},{id:'rapido2_uhf'}],gantries:[{id:'filamatrix_6'},{id:'madmax_12_6'}],carriages:[{id:'filamatrix'},{id:'madmax_xol'}],probes:[{id:'none'}],boards:[{id:'none'}],cooling_options:[{id:'source'}]};
for(const extruder of ['cw2','galileo2'])for(const hotend of c.hotends.map(h=>h.id))c.variants.push({id:`filamatrix_${extruder}_${hotend}`,toolhead:'stealthburner',mount:'filamatrix',extruder,hotend,gantry:'filamatrix_6',carriage:'filamatrix',probe:'none',board:'none',cooling:'source',belt_width_mm:6,registration_source:'filamatrix',base_asset:hotend.includes('uhf')?'uhf_front':'standard_front',base_hidden_keys:[],head_translation_mm:[0,0,0],modules:[{id:extruder+'_cutter_body',translation_mm:[0,0,0],role:'tool'},{id:hotend+'_cartridge',translation_mm:[0,0,0],role:'tool'},{id:'filamatrix_carriage',translation_mm:[0,0,0],role:'shuttle'}],notes:[],fit:{nozzle_mm:[0,0,hotend.includes('uhf')?-8.5:0]}});
const madmax={...c.variants[0],id:'madmax_xol',toolhead:'xol',mount:'madmax',extruder:'sherpa_mini',hotend:'rapido2_uhf',gantry:'madmax_12_6',carriage:'madmax_xol',registration_source:'madmax_xol',base_asset:'xol',head_translation_mm:[0,-1.74,-360],modules:[{id:'madmax_carriage',translation_mm:[0,0,0],role:'shuttle'},{id:'madmax_plate',translation_mm:[0,0,0],hidden_keys:['alternate_plate'],role:'tool'},{id:'dock',translation_mm:[-80,0,0],role:'dock'}],fit:{nozzle_mm:[0,-26,-58]}};c.variants.push(madmax);
const original=JSON.stringify(c);const installed=machineHeadVariants(c,reg,'voron_trident_350');assert.equal(installed.length,9);assert.equal(machineHeadVariants(c,reg,'siboor_trident_350','siboor_awd').length,0);
for(const v of c.variants){const plan=headPlan(v);assert.equal(plan.base,v.base_asset);const pose=installedHeadPlan(v,reg,reg.machines.voron_trident_350);assert(pose.nozzle_mm.every(Number.isFinite));assert(!pose.modules.some(m=>m.role==='dock'));assert(pose.modules.some(m=>m.role==='shuttle'));const link=headPrinterLink(v,reg,'https://example.test/viewer/toolheads.html?lang=en');assert.equal(link.machine,'voron_trident_350');assert.equal(new URL(link.url).searchParams.get('lang'),'en')}
assert.deepEqual(installedHeadPlan(madmax,reg,reg.machines.voron_trident_350).modules.find(m=>m.id==='madmax_plate').hidden_keys,['alternate_plate']);
for(const v of c.variants)for(const field of c.dimensions)for(const option of choicesFor(c,v,field)){const next=resolveVariant(c,{...v,[field]:option.id},field);assert.equal(next[field],option.id);assert(c.variants.includes(next))}
const g2=resolveVariant(c,{...c.variants[0],extruder:'galileo2'},'extruder');assert.equal(g2.extruder,'galileo2');assert(!g2.modules.some(m=>m.id==='cw2_cutter_body'));
const uhf=resolveVariant(c,{...c.variants[0],hotend:'rapido2_uhf'},'hotend');assert.equal(uhf.base_asset,'uhf_front');assert(!uhf.modules.some(m=>m.id==='revo_voron_cartridge'));
assert.equal(JSON.stringify(c),original);
console.log('Cutter housing/cartridge replacement, MadMax native datum, 6/9 mm scope, source links and dependent choices passed.');
